let persons = "eyJoZmtucXR0IjogIkZsb3JpIiwgIm1jZmduZXMiOiAiQm90ZXoiLCAib2JsYmxnaCI6ICJEaWFuYSIsICJkaWZuZGl2IjogIlN0ZWZhbmlhIiwgImttY3JkbWIiOiAiR2V0YSIsICJnc2Zya3VnIjogIkZsb3JpY2EiLCAic2JsaG1rdSI6ICJJbmEiLCAidWl3dXd6YSI6ICJWYWxlbnRpbiIsICJzeXNlbG1iIjogIklsaWUiLCAiaHd1enVwYSI6ICJGbG9yZW50aW5hIiwgImlxZ3htZnkiOiAiQWxleCIsICJnamF2emJ5IjogIlJvZGljYSBzaSBJb25lbCIsICJvc2Vxc2FpIjogIk9sZ2Egc2kgRmxvcmluIiwgInlmYXNvaG0iOiAiQW5kcmEiLCAibmN6Y3N2ZSI6ICJNaXRzdXJpIiwgIm9reHZvZXoiOiAiTWFtbyIsICJodnprdHdrIjogIkxpYW5hIiwgImJmbnhldW4iOiAiQ3Jpc3RpbmEiLCAid25lb2NueSI6ICJNb3NpbG9yIiwgInl0ZXhybXMiOiAiR3JpZ29yZSIsICJ0Ym1ydWZ5IjogIkNvc21pbiBzaSBBbmEiLCAib25nZHR0cyI6ICJBZGEiLCAibHF2ZXR3cyI6ICJSYXJlcyIsICJzempoYnlsIjogIkV1Z2VuIiwgImljbXppZ2QiOiAiRmFtaWxpYSBWbGFkIiwgInllcXNzcWIiOiAiRmFtaWxpYSBTYWxhamFuIiwgImlnbml3ZGsiOiAiQW5kcmVlYSIsICJjamVrdXJyIjogIklvbmVsYSIsICJvdGJ3c3J3IjogIk1vc2ljYSIsICJpbm5jcnhtIjogIkdpbGx5IiwgInJpZ2N3bWQiOiAiQ3Jpc3RpIiwgInJ1cGNyZ3oiOiAiQW5jYSBzaSBTZWJpIiwgImZicHVzZ3YiOiAiU29yaW4iLCAiZmJod3V6eiI6ICJWYWxpIiwgIm9ka3d5eG0iOiAiTGF1cmEiLCAic3JzcnpsbSI6ICJGYW1pbGlhIFBvcGEiLCAic21sZXp4YyI6ICJOZWxhIiwgInVldXJ5amEiOiAiQWxleCIsICJmbnpmZmF5IjogIk92aWRpdSIsICJvcGxhbGljIjogIkFsZXhhbmRyYSIsICJyZm1jZXhqIjogIkFuZHJlaSIsICJyamxhZnh1IjogIlJhZHUgc2kgR2FiaSIsICJlZGphb2pwIjogIk1vbmljYSIsICJtcWJ0dm9wIjogIk1hcmlhIiwgInVwbGZ5cHkiOiAiQ29jbyIsICJqZmdjanVzIjogIkxpbGkiLCAiZ2plZ3NlayI6ICJOYXNpaSBub3N0cmkgZHJhZ2kiLCAid3l2dW56biI6ICJUdXR1IiwgIm1xaXNwb2YiOiAiUHVpdSIsICJiZGd5YnlnIjogIlNvZmkiLCAibXJmaHlpcSI6ICJGYW1pbGlhIFNjdXRhcml1IiwgInhvYnV1aGwiOiAiQWxleCIsICJkdHpvd3R4IjogIk5lbHUiLCAieXlma2t1diI6ICJBZGkiLCAiZmhzY296eSI6ICJHZW9yZ2UiLCAic3phb3B5byI6ICJGYW1pbGlhIFBvcGEiLCAia2RtdWhudSI6ICJNdWd1cmVsIiwgImdwZnBydmEiOiAiRmFtaWxpYSBNYXJpbmVzY3UiLCAiZWJxanFlcSI6ICJNaXJjZWEiLCAic2Jpb2NjaSI6ICJJb24iLCAiZ2FheXpqZiI6ICJTdGVmYW4gc2kgRW5lIiwgImZvZ3NkdWIiOiAiR2VvcmdpY2EiLCAibm15enpiYyI6ICJDb3NtaW5hIiwgImR1b3docWIiOiAiRmFtaWxpYSBUb251IiwgImdndXdxcnoiOiAiRmFtaWxpYSBWZXJndSIsICJyZXVla2JhIjogIkFudG9uIiwgInZtZmt6eHYiOiAiQW5kcmVlYSIsICJyY21xamVhIjogIkZhbWlsaWEgSXNhYyIsICJsbm9yYndqIjogIkx1bWluaXRhIiwgImp6ZWNkZHoiOiAiRmFtaWxpYSBBbmRyZWkiLCAidmRmcWN5ZiI6ICJDYXRhIHNpIFBhcnZpIiwgImppamdkY2siOiAiQWxleGFuZHJ1IiwgIm9vbndoeG4iOiAiSW9hbmEiLCAicW5jZXFwbCI6ICJNYXJpYW5hIiwgImNoY2ZlY2siOiAiTWFyaWFuYSIsICJqa2dxZGtqIjogIkRhbmkiLCAiZ2Zic2NycSI6ICJGYW1pbGlhIFNhbmR1IiwgInNpcGN3aXkiOiAiQm9nZGFuIiwgImthYW5rbXIiOiAiQW5hIHNpIExlbyIsICJxa3RoZ3J5IjogIkFuZHJlaSBzaSBSYWx1Y2EiLCAibHlranhoYSI6ICJNYXhpbSIsICJmYXR5Z21mIjogIlZhbGkiLCAibXBsb2FoaiI6ICJEYW5hIiwgInh1ZnBmb3MiOiAiQ2FybWVuIiwgImFkcXBkY20iOiAiRWxlbmEiLCAicnFkYXRzbCI6ICJGZWxpY2lhIiwgImF2dWVja2giOiAiQ3Jpc3RpbmEgc2kgQWxleCIsICJiY3RlemFjIjogIlZpbyIsICJ3bmJqZm15IjogIlRhdGlhbmEifQ";
let encoder={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(e){var t="";var n,r,i,s,o,u,a;var f=0;e=encoder._utf8_encode(e);while(f<e.length){n=e.charCodeAt(f++);r=e.charCodeAt(f++);i=e.charCodeAt(f++);s=n>>2;o=(n&3)<<4|r>>4;u=(r&15)<<2|i>>6;a=i&63;if(isNaN(r)){u=a=64}else if(isNaN(i)){a=64}t=t+this._keyStr.charAt(s)+this._keyStr.charAt(o)+this._keyStr.charAt(u)+this._keyStr.charAt(a)}return t},decode:function(e){var t="";var n,r,i;var s,o,u,a;var f=0;e=e.replace(/[^A-Za-z0-9+/=]/g,"");while(f<e.length){s=this._keyStr.indexOf(e.charAt(f++));o=this._keyStr.indexOf(e.charAt(f++));u=this._keyStr.indexOf(e.charAt(f++));a=this._keyStr.indexOf(e.charAt(f++));n=s<<2|o>>4;r=(o&15)<<4|u>>2;i=(u&3)<<6|a;t=t+String.fromCharCode(n);if(u!=64){t=t+String.fromCharCode(r)}if(a!=64){t=t+String.fromCharCode(i)}}t=encoder._utf8_decode(t);return t},_utf8_encode:function(e){e=e.replace(/rn/g,"n");var t="";for(var n=0;n<e.length;n++){var r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r)}else if(r>127&&r<2048){t+=String.fromCharCode(r>>6|192);t+=String.fromCharCode(r&63|128)}else{t+=String.fromCharCode(r>>12|224);t+=String.fromCharCode(r>>6&63|128);t+=String.fromCharCode(r&63|128)}}return t},_utf8_decode:function(e){var t="";var n=0;var r=c1=c2=0;while(n<e.length){r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r);n++}else if(r>191&&r<224){c2=e.charCodeAt(n+1);t+=String.fromCharCode((r&31)<<6|c2&63);n+=2}else{c2=e.charCodeAt(n+1);c3=e.charCodeAt(n+2);t+=String.fromCharCode((r&15)<<12|(c2&63)<<6|c3&63);n+=3}}return t}}

function getParameterByName(name) {
    url = window.location.href;
    name = name.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
        results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, " "));
}

function getPersonName() {
    let code = getParameterByName('code');
    let codes = eval('(' + encoder.decode(persons) + ')');
    let res = codes[code];
    return {personName: res, page: res ? "page_success.html" : "page_error.html"};
}
